### ISSUE TITLE
To latin1 didn't work

### ISSUE THREAD

**Issue by Tom29** [neitanod/forceutf8#36]
i've tried with pure utf8 string:
$s = 'Những Ca Khúc Nhạc Vàng';

and utf8 mixed:
$s = 'Nhá»¯ng Ca KhÃºc Nháº¡c VÃ ng';

to latin1 but didn't worked.

**Comment by neitanod** [comment]
What output did you expect and what output did you get?
Could you please post a gist of the source code of your test?

Also, notice that Latin1 is a very limited encoding and not all UTF8 strings can be expressed with it.

**Comment by Tom29** [comment]
the first string must be the same with the second one. if you use ```utf8_decode``` for the second string you'll see the same string with the first one.

**Comment by neitanod** [comment]
Would you be so kind to post a working gist of your case using https://gist.github.com/ and paste the link here.
