### ISSUE TITLE
Incorrect PHP Version Requirement in composer.json?

### ISSUE THREAD

**Issue by ChadSikorra** [neitanod/forceutf8#37]
I was looking at the composer.json and noticed it lists `"php": ">=5.2.0"`. Shouldn't that be `"php": ">=5.3.0"` since the code is namespaced?

**Comment by neitanod** [comment]
Fixed.  Thanks!

--
Sebastián Grignoli

2015-01-01 17:48 GMT-03:00 Chad Sikorra <notifications@github.com>:
