### ISSUE TITLE
PCDATA invalid Char value 31

### ISSUE THREAD

**Issue by math62400** [neitanod/forceutf8#39]
First of all, thanks !! 
Your tools helps me a lot for UTF8 string conversion

I would save a string in XML and I would like to format it in UTF8, 
But I have this error when I try to load XML after save.
```
DOMDocument::load(): PCDATA invalid Char value 31
```
I look for an answer in Google and I found that.

http://stackoverflow.com/questions/14463573/php-simplexml-load-file-invalid-character-error

```php
function utf8_for_xml($string)
{
    return preg_replace ('/[^\x{0009}\x{000a}\x{000d}\x{0020}-\x{D7FF}\x{E000}-\x{FFFD}]+/u', ' ', $string);
}
```

Can you tell me if there is an other way to solve it?

Mathieu

**Comment by oxxido** [comment]
Hey, you probably already solve it, but this is nothing to do with utf8 (specifically):

> When you put utf-8 encoded strings in a XML document you should remember that not all utf-8 valid > chars are accepted in a XML document http://www.w3.org/TR/REC-xml/#charsets
> So you should strip away the unwanted chars, else you’ll have an XML fatal parsing error 

from http://www.phpwact.org/php/i18n/charsets

**Comment by neitanod** [comment]
Thanks oxxido!
