### ISSUE TITLE
simple quote encoding

### ISSUE THREAD

**Issue by BenJaziaSadok** [neitanod/forceutf8#40]
Hello, i use forceutf8 to encode some of email bosy in php imap.
I find an issue to encode simple quote.
It appears like '?'
Any method to fix this?

**Comment by hugsbrugs** [comment]
yes I have same problem here !

**Comment by hugsbrugs** [comment]
Found a workaround :

```
function fixcurly($string)
{ 
    $search = array("\xe2\x80\x9c", "\xe2\x80\x9d", "\xe2\x80\x98", "\xe2\x80\x99");
    $replace = array('"', '"', "'", "'");
    return str_replace($search, $replace, $string);
}
```

**Comment by neitanod** [comment]
Could you post a snippet of your code (the part that calls the Encoding function) along with some example data?  (please use pastebin to keep original encoding of that data)

**Comment by dasDaniel** [comment]
I have the same issue when using `Encoding::fixUTF8(...)`

the issue is the right single quotation mark (DEC:146/ HEX:92)
