### ISSUE TITLE
Packagist was not updated with the new tags

### ISSUE THREAD

**Issue by byjg** [neitanod/forceutf8#45]
First of all thank you for create the tags. 

Now, packagist did not updated with these tags. I realize that the package neitanod/forceutf8 does not belongs to you neither to a any forceutf8 developer. I already contact the owner of packagist (https://github.com/nidelson) but there is no answer. 

I suggest you to claim the ownership of this package to avoid this happens again. The packagist email is contact@packagist.org. 

Sorry If I am boring you but I prefer the project to be maintained by the creator instead to create a fork and separate the codes.

**Comment by neitanod** [comment]
You are not boring me, in fact you are contributing to the project with this.

Nidelson also contributed by submitting forceUTF8 to packagist in the first place, but now it would be helpful if he transferred me the administration of the package, but, like you, I couldn't reach him.

The last time I updated the tags packagist updated automatically, but it took some time.

I don't know if there is any formal procedure of claiming ownership of a package.

**Comment by byjg** [comment]
Well, I never had this problem before. I believe if you asking directly to the packagist's contact maybe solve this.

For now I am using the tags by adding this to my composer.josn:

```
    "require": {
        "neitanod/forceutf8": "v2.0"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/neitanod/forceutf8"
        }
    ],
```

**Comment by neitanod** [comment]
Good news!  
I am the administrator of the Packagist entry now, so this issue is solved.  :)
