### ISSUE TITLE
script breaks two-byte (e.g. Czech) symbols

### ISSUE THREAD

**Issue by omnomnymous** [neitanod/forceutf8#52]
``` 
$ cat a.php
<?php
require_once('Encoding.php');
use \ForceUTF8\Encoding;
$str = 'šřěī';
$newstr = Encoding::fixUTF8($str);
var_dump($str);
var_dump($newstr);

$ php a.php
string(8) "šřěī"
string(4) "????"
```

**Comment by neitanod** [comment]
fixUTF8 is intended to work on broken strings -utf8_encoded() more than once in PHP- and only preserves Latin1 characters.
Use toUTF8() to convert mixed-encoding (also corrupted, but in a way that's different from the above case) strings to UTF8 strings.
