### ISSUE TITLE
Some characters not correctly decoded ?

### ISSUE THREAD

**Issue by gordielachance** [neitanod/forceutf8#59]
Hi, is it possible that the characters 
`“ ” `
are not correctly decoded ?

**Comment by Krato** [comment]
Yes. This is giving me an error to

**Comment by neitanod** [comment]
Not likely.  What encoding are you using in the input?

**Comment by M13K** [comment]
what if you don't know what encoding used in the input. I have a csv file with an unknown charset, then 
i've applied the Encoding::toUTF8. Unfortunately, it does'nt work...

**Comment by neitanod** [comment]
ForceUTF8 will process your file correctly as long as it's encoded in Latin1 (iso 8859-1), Windows-1252 or UTF8, or mix of them.  ForceUTF8 does not understand other encondings.

**Comment by M13K** [comment]
Ok, thanks you for the reply! Hope to find what i'm looking for. Good job by the way..

**Comment by stamster** [comment]
@neitanod supported encodings should be clearly listed in a documentation.

ATM:
> You don't need to know what the encoding of your strings is. It can be Latin1 (iso 8859-1), Windows-1252 or UTF8, or the string can have a mix of them. \ForceUTF8\Encoding::toUTF8() **will convert everything to UTF8**.

**Comment by neitanod** [comment]
Right.  I initially wrote it for my own needs but it's probably time to write a better documentation now that the user base has grown.   :)
