### ISSUE TITLE
toUTF8() return Invalid UTF-8 ?

### ISSUE THREAD

**Issue by petrich** [neitanod/forceutf8#61]
Hi there
great lib. Works nearly perfectly on my project.
However, it seems that sometimes ```toUTF8()``` returns an invalid  utf8-encoded string.

See this example:
```php
$utf8_string = \ForceUTF8\Encoding::toUTF8(base64_decode('PGk+PCFbQ0RBVEFbMS4gUGVyZm9ybWFuY2UgYW5kIMxm5mdi9G504WF56atlOiBHZW5yZSwgS25vd2xlZGdlLCBhbmQgUG9saXRpY3MgIDIuIEEgQ3JpdGlxdWUgb2YgWW9y+WLhIEp1ZGdtZW50OiBJbmRpdmlkdWFsIEF1dGhvcml0eSwgQ29tbXVuaXR5IENyZWF0aW9uLCBhbmQgdGhlIEVtYm9kaW1lbnQgb2YgwKv3PEJSPjMuIFdoYXQgTWF0dGVyIFdobyBEYW5jZXM6IFNlbGYtZmFzaGlvbmluZywgKG5vbilTdWJqZWN0cywgYW5kIHRoZSBOYXRpb248QlI+NC4gTm8gVmljdG9yLCBubyBWYW5xdWlzaGVkLCBubyBQYXN0OiBPbGEgUm90aW1pLCBZYWt1YnUgR293b24sIFNhbmkgQWJhY2hhLCBhbmQgICcgJ1RoZSBFbmQgb2YgTmlnZXJpYW4gSGlzdG9yeSAnICc8QlI+NS4gVmFsdWVzIGJleW9uZCBFdGhpY3M6IEZyb20gU3RlbGxhIERpYSBPeWVkZXBvIHRvIFRlc3MgT253dWVtZTxCUj42LiBDb25jbHVzaW9uczogQ2l2aWwgR292ZXJuYW5jZSBhbmQgdGhlIFBvbGl0aWNzIG9mIFlvcvli4SBUaGVhdHJlPEJSPkJpYmxpb2dyYXBoeTxCUj5JbmRleDxCUj4gIF1dPjwvaT4NCg=='));

var_export(mb_check_encoding($utf8_string, 'UTF-8'));
``` 
Should print "true" but got "false".

Any Ideas?

Thank you

**Comment by neitanod** [comment]
What are the characters in "and the Embodiment of ���<BR>" supposed to be?

**Comment by petrich** [comment]
Hi
i can not say it because the data-content is completely unkown for me (i have to import millions of text strings to utf8 from unkown and even different chartsets charsets... )

My Workaround is currently for such Content fixUTF8()... works but i was wondering why toUTF8() produce in some cases invalid utf8.

Maybe you can find a solution.

Greetings

**Comment by neitanod** [comment]
Because it works in a character by character basis, fixing whatever it can, and leaving what it does not understand just like it was.
