### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by andreapernici** [neitanod/forceutf8#63]
Trying on this word but not working at all. Also tried the example but not working.

MedveÄ‘a

**Comment by manzari** [comment]
Afaik all chars in the word "MedveÄ‘a" are UTF-8. Do you mean "Medveđa"? (with [small letter d with stroke](http://www.charbase.com/0111-unicode-latin-small-letter-d-with-stroke))
What behaviour are you experiencing? What behaviour are you expecting?
