### ISSUE TITLE
Not converting Japanese/Korean strings 

### ISSUE THREAD

**Issue by Transferer** [neitanod/forceutf8#65]
Am i just doing something wrong? giving it a japanese string is returning this: ?±?ê??e?X?g??·

**Comment by neitanod** [comment]
What encoding is your japanese string on?
If it's using UTF8 it should be kept unchanged.
Other japanese encodings are not supported.

**Comment by Transferer** [comment]
I figured my problem out. It was coming out in SHIFT-JIS but i just changed my approach to the problem and in the end didn't need to use this project to help me.

Will close this.
