### ISSUE TITLE
Not converting ISO-8859-2

### ISSUE THREAD

**Issue by mikemix** [neitanod/forceutf8#66]
As said, toUTF8 method does not convert properly latin special characters from ISO-8859-2 encoding.

**Comment by garrettw** [comment]
It would be courteous for you to state the expected result and the actual result of your usage attempt rather than expecting someone else to figure out how you came to this conclusion.

**Comment by neitanod** [comment]
ISO-8859-2 is not supported.  Only ISO-8859-1 and Win-1252 are supported.
