### ISSUE TITLE
Problem when convert string

### ISSUE THREAD

**Issue by guytzhak** [neitanod/forceutf8#67]
When I convert PHP string that comve from csv it's not working.
when I Copy paste the string content to another string like:
$text = "\xd7\x99\xd7\x95\xd7\x94\xd7\xa0\xd7\xa1\xd7\x91\xd7\x95\xd7\xa8\xd7\x92";

it's working...

What we can do? it's the same content....

**Comment by garrettw** [comment]
This is very vague. Please tell us your exact input, the output you expect, and the output you actually get. It might also be helpful to know the character encoding of your input string.

**Comment by neitanod** [comment]
If I feed the library with the input you provided: "יוהנסבורג"
Encoding::toUTF8("יוהנסבורג") returns the same string, which means it works.
Encoding::fixUTF8("יוהנסבורג") doesn't work, obviously, because it's intended for Latin1 / Win1252 characters only.
