### ISSUE TITLE
Latin-2 support (ISO 8859-2)

### ISSUE THREAD

**Issue by dakujem** [neitanod/forceutf8#69]
**Feature request**

It would be really nice if it could also work with ISO 8859-2 (Latin-2) charset.

**Comment by redolent** [comment]
Could you provide a test case?

Example:
```
use \ForceUTF8\Encoding;
$iso8859_2_string = "my string";
$encoded = Encoding::toUTF8( $iso8859_2_string );
echo $encoded;
```

**Comment by dakujem** [comment]
Hey, sorry for long pause. I realised, for this library to be generally useful in my region, it would have to be able to recognize many more formats. In Central Europe, for example, we use ISO 8859-2 and Win1250 simultaneously. And there are more for other parts of Europe: ISO 8859-1, ISO 8859-2, ISO 8859-3, Win1250, Win1252...
I'm not sure it is the goal of this lib to do it.
