### ISSUE TITLE
Problem with Ã™ character

### ISSUE THREAD

**Issue by GiacomoK** [neitanod/forceutf8#70]
Hi,
first of all thanks for this library, its excellent.  
I have a problem with this database field:

Come stai? (PIÃ™ RISPOSTE POSSIBILI)

Useing this library I get this:

Come stai? (PIÃ? RISPOSTE POSSIBILI)

The database collation is latin1_swedish_ch while the charset of the table is utf8_general_ci.

**Comment by garrettw** [comment]
It looks like your intended character may not have posted here correctly either. Could you specify exactly what character it is that you're intending?

**Comment by GiacomoK** [comment]
This is this character

    Ù

**Comment by garrettw** [comment]
That character is supported by this library, but the issue could be coming from your database table's charset.

I would try changing your table's charset to either `Latin1` or `utf8mb4` and see if that fixes it.

(Source: [Breaking out from the MySQL character-set hell](https://medium.com/@manish_demblani/breaking-out-from-the-mysql-character-set-hell-24c6a306e1e5))

**Comment by kasperkamperman** [comment]
I tried this library in order to solve a similar problem, however it didn't work for me. 

Doing some more research I've made this fix. 
https://gist.github.com/kasperkamperman/198c6389840532b96069ba6a776d69e6
