### ISSUE TITLE
Encoding em/en-dash

### ISSUE THREAD

**Issue by hugopakula** [neitanod/forceutf8#74]
Given the following code sample:
```
var_dump($em_dash = '—'); // em-dash is U+2014
var_dump($en_dash = '–'); // en-dash is U+2013

var_dump(\ForceUTF8\Encoding::fixUTF8($em_dash)); // Breaks em-dash
var_dump(\ForceUTF8\Encoding::toUTF8($em_dash)); // Valid em-dash
var_dump(\ForceUTF8\Encoding::fixUTF8($en_dash)); // Breaks en-dash
var_dump(\ForceUTF8\Encoding::toUTF8($en_dash)); // Valid en-dash

var_dump($mixed = 'FÃ©dÃ©ration Camerounaise—de–Football');  // Mixed string with non-utf8 encoded chars, em and en-dash
var_dump(\ForceUTF8\Encoding::fixUTF8($mixed)); // Breaks em/en-dash, valid other chars
var_dump(\ForceUTF8\Encoding::toUTF8($mixed)); // Breaks other chars, valid em/en-dash
```

We get the following output:
```
string(3) "—"
string(3) "–"
string(1) "?"
string(3) "—"
string(1) "?"
string(3) "–"
string(45) "FÃ©dÃ©ration Camerounaise—de–Football"
string(37) "Fédération Camerounaise?de?Football"
string(45) "FÃ©dÃ©ration Camerounaise—de–Football"
```

Em/en-dash are both in the utf8 range, however, `Encoding::fixUTF8` fails with the characters by outputting a `?`. Both fixUTF8 and toUTF8 should output a valid em/en-dash.

Is there a way to combine these functions to output a valid string of mixed utf8/non-utf8 encoded chars?

**Comment by neitanod** [comment]
Try one of this variations:
`        \ForceUTF8\Encoding::fixUTF8($str, ForceUTF8\Encoding::ICONV_IGNORE);`
or
`        \ForceUTF8\Encoding::fixUTF8($str, ForceUTF8\Encoding::ICONV_TRANSLIT);`

**Comment by hugopakula** [comment]
Thanks @neitanod for providing a working solution. It is clear what the functionality of such options are as per the iconv docs, but it would be worthwhile adding these options to the README for future users of this helpful class.
