### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by shoutinblues** [neitanod/forceutf8#90]
This will probably seem to be a stupid question, but I can't figure out how to use this program.

When I run this on the command line:   php echo Encoding::fixUTF8("FÃ©dÃ©ration Camerounaise de Football");  

I get an error message: -bash: syntax error near unexpected token `('

I'm using CentOS 7.  I am a system administrator with no software development experience.  I am not able to look at code and determine how to use it.  Could you possibly add some instructions for people at my level?

**Comment by quyle92** [comment]
have you put `use \ForceUTF8\Encoding; ` at the top of the page?

**Comment by neitanod** [comment]
Save this into a file:

https://gist.github.com/neitanod/7ad4bd57fb7e68e5856c93f31cd66b3a

Put it in your path, change it's permissions to make it executable, (and of course make sure you also have the library available in the same folder, or alternatively point to the library file by changing the include in line 4 of the script), and then run:

`forceutf8 --help`

You'll get:

    $ forceutf8 --help
    Specifiy the file to convert or pipe some text.
    
    Example 1:
        ls | forceutf8
    
    Example 2:
        forceutf8 input_file.txt  # will output converted text
    
    Example 3:
        forceutf8 input_file.txt replace  # will replace file contents
